auto: true
paginate: 10
permalink: /:year/:month/:day/:title/
pygments: true
url: http://geoff.greer.fm
author: Geoff Greer
title: Geoff's Site
exclude:
  - new_post.sh
  - less.sh

disqus_shortname: ggreer

gallery_dir: photos
galleries:
  chile_trip:
    best_image: IMG_1068.JPG
  japan_trip:
    best_image: IMG_0690.JPG
  best:
    best_image: snaileo_gonzales.jpg
  sf_from_bernal_heights:
    best_image: DSC_7861.JPG
  thermite:
    best_image: P1010014_crop.jpg
  burning_man_2010:
    best_image: DSC_8021.JPG
  burning_man_2009:
    best_image: DSC_4302.JPG
  china_trip:
    best_image: IMG_0288.JPG
  "my_new_used_SV-650-S":
    best_image: FILE0042.JPG
  marathon:
    best_image: 04.jpg
  ammo_case:
    best_image: DSCF0006.JPG
