# Jekyll 3 seems to not interact well with rdiscount/discount. Use default markdown processor for now.
# markdown: rdiscount
# rdiscount:
#   extensions: [smart, strict]
paginate: 10
permalink: /:year/:month/:day/:title/
highlighter: pygments
url: http://geoff.greer.fm
author: Geoff Greer
title: Geoff's Site
exclude:
  - new_post.sh
  - less.sh
  - upload.py

disqus_shortname: ggreer

gems:
  - jekyll-gallery-generator
  - jekyll-paginate
  - jekyll-sitemap

gallery:
  title_prefix: "Photos: "
  dir: photos
  symlink: true
  galleries:
    idaho_hot_springs_loop_2016:
      best_image: IMG_0363.jpg
    big_sur_2016:
      best_image: DSC_1362.jpg
    snowshoeing_2015:
      best_image: DSC_1251.jpg
    desolation_wilderness_2015:
      best_image: IMG_1313.jpg
    pride_parade_2015:
      best_image: DSC_0165.jpg
    backgrounds:
      hidden: true
    pics:
      hidden: true
    me:
      hidden: true
    screenshots:
      hidden: true
      sort_reverse: true
    yc_slideshow:
      name: "YC Slideshow"
      best_image: 15.jpg
      hidden: true
    taiwan_2015:
      best_image: IMG_1088.JPG
    tahoe_trip_2014:
      best_image: IMG_0786.JPG
      hidden: true
    banff_trip_2014:
      best_image: IMG_0670.jpg
    christmas_vacation_2012:
      best_image: DSC_0226.jpg
    chile_trip:
      best_image: IMG_1068.JPG
    japan_trip:
      best_image: IMG_0690.JPG
    best:
      best_image: snaileo_gonzales.jpg
    cloudkick_office:
      best_image: DSC_8280.JPG
    sf_from_bernal_heights:
      best_image: DSC_7861.JPG
    thermite:
      best_image: P1010014_crop.jpg
    burning_man_2010:
      best_image: DSC_8021.JPG
    burning_man_2009:
      best_image: DSC_4302.JPG
    china_trip:
      best_image: IMG_0288.JPG
    "my_new_used_SV-650-S":
      name: "My New Used SV650/S"
      best_image: FILE0042.JPG
    marathon:
      best_image: 04.jpg
    ammo_case:
      best_image: DSCF0006.JPG
  thumbnail_size:
    x: 800
    y: 800
