auto: true
paginate: 10
permalink: /:year/:month/:day/:title
pygments: true
url: http://geoff.greer.fm
author: Geoff Greer
title: Geoff's Site
exclude: deploy_site.sh new_post.sh

gallery_dir: photos
galleries:
  chile_trip:
    best_image: IMG_1068.JPG
  japan_trip:
    best_image: IMG_0690.JPG
  best:
    best_image: snaileo_gonzales.jpg
  sf_from_bernal_heights:
    best_image: DSC_7861.JPG
  thermite:
    best_image: P1010014_crop.jpg
